name: Deploy Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      url:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to ${{ inputs.environment }}
        run: |
          echo "Deploying to ${{ inputs.environment }}..."
          # Add your deployment script here
          # Example for an SSH deployment:
          # scp -r ./dist user@your-server:/var/www/${{ inputs.environment }}

      - name: Notify deployment success
        if: success()
        run: echo "Deployment to ${{ inputs.environment }} successful!"
