name: Update Deployment Status

on:
  workflow_dispatch:
    inputs:
      deployment_id:
        description: 'Deployment ID to update'
        required: true
      status:
        description: 'Deployment status (e.g., in_progress, success, failure)'
        required: true
        default: 'in_progress'
      log_url:
        description: 'Optional: URL to deployment logs'
        required: false

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
      - name: Update Deployment Status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const deploymentId = '${{ github.event.inputs.deployment_id }}';
            const status = '${{ github.event.inputs.status }}';
            const logUrl = '${{ github.event.inputs.log_url }}';

            // Update Deployment Status
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deploymentId,
              state: status,
              log_url: logUrl || undefined
            });

            console.log(`Deployment ${deploymentId} status updated to ${status}`);
