name: Deploy Chain to Production

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

concurrency:
  group: 'deploy'
  cancel-in-progress: true

jobs:
  deploy-staging:
    name: Deploy to Staging
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      url: https://your-staging-app.com

  wait-for-deploy-and-run-e2e-testing:
    name: Wait for Deploy and Run Integration Checks
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Run Integration Tests
        run: echo "Integration tests passed"

  deploy-prod-wave1:
    name: Deploy to Prod Wave 1
    needs: wait-for-deploy-and-run-e2e-testing
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod-wave1
      url: https://your-prod-wave1-app.com
      
  monitor-metrics-wave1:
    name: Monitor Metrics for Wave 1
    runs-on: ubuntu-latest
    needs: deploy-prod-wave1  # Corrected dependency
    steps:
      - name: Check Metrics
        run: echo "Metrics monitoring passed"
      
  deploy-prod-wave2:
    name: Deploy to Prod Wave 2
    needs: monitor-metrics-wave1
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod-wave2
      url: https://your-prod-wave2-app.com
