name: Deploy to Production

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    environment:
      name: production2  # Specify the environment as 'production'
      url: https://your-production-app.com  # Optional: Add URL for the environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to Production Server
        run: |
          echo "Deploying to production..."
          # Add your deployment script here
          # Example for an SSH deployment:
          # scp -r ./dist user@your-server:/var/www/app
          
      - name: Notify deployment success
        if: success()
        run: echo "Deployment successful!"
