name: Test

on:
  push:

permissions:
  id-token: write
  contents: write
  deployments: write
  
jobs:
  get-sha:
    runs-on: ubuntu-latest
    steps:
    - name: Bump Version Using GitHub Script
      id: bump
      uses: actions/github-script@v7
      with:
        script: |
          const { data: tags } = await github.rest.repos.listTags({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 1
          });
          
          const latestTag = tags.length > 0 ? tags[0].name : '0.0.0';
          const [major, minor, patch] = latestTag.split('.').map(Number);
          const newVersion = `${major}.${minor}.${patch + 1}`;
          console.log(newVersion)
          await github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `refs/tags/${newVersion}`,
            sha: context.sha
          });

          core.setOutput('new_version', newVersion);
